sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t complex/react-test -f client/Dockerfile.dev ./client

script:
  - docker run -e CI=true complex/react-test npm run test

after_success:
  - docker build -t taufinaiden/multi-client ./client
  - docker build -t taufinaiden/multi-nginx ./nginx
  - docker build -t taufinaiden/multi-server ./server
  - docker build -t taufinaiden/multi-worker ./worker

  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push the images to docker hub
  - docker push taufinaiden/multi-client
  - docker push taufinaiden/multi-nginx
  - docker push taufinaiden/multi-server
  - docker push taufinaiden/multi-worker