sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t taufinrusli/react-test -f client/Dockerfile.dev ./client

script:
  - docker run -e CI=true taufinrusli/react-test npm run test

after_success:
  - docker build -t taufinrusli/multi-client ./client
  - docker build -t taufinrusli/multi-nginx ./nginx
  - docker build -t taufinrusli/multi-server ./server
  - docker build -t taufinrusli/multi-worker ./worker

  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push the images to docker hub
  - docker push taufinrusli/multi-client
  - docker push taufinrusli/multi-nginx
  - docker push taufinrusli/multi-server
  - docker push taufinrusli/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-185187793419"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY